version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing Terraform...
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform version
      - echo Installing tfsec and checkov...
      - curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - pip install --no-cache-dir checkov

  pre_build:
    commands:
      - echo Checking Terraform formatting...
      - terraform fmt -check -recursive || echo "Format check warnings"
      - echo Validating Terraform configuration...
      - terraform validate || echo "Validation warnings (non-blocking)"
      - echo Running tfsec security scan (non-blocking)...
      - tfsec . --no-color || echo "tfsec completed with warnings"
      - echo Running checkov security scan (non-blocking)...
      - checkov -d . || echo "checkov completed with warnings"
      - echo Initializing Terraform...
      - terraform init -input=false

  build:
    commands:
      - echo Planning Terraform changes...
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo Applying Terraform changes...
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
